### ISSUE TITLE
Redis libraries on codenvy/python27

### ISSUE THREAD

**Issue by aussiev** [codenvy/dockerfiles#26]
got this error when trying to build python27 based docker file that pip'd redis

Collecting redis (from -r requirements.txt (line 2))
  Downloading redis-2.10.3.tar.gz (86kB)
Installing collected packages: redis
  Running setup.py install for redis

    error: could not create '/usr/local/lib/python2.7/dist-packages/redis': Permission denied

    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-AgNs9i/redis/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pAs10o-record/install-record.txt --single-version-externally-managed --compile:
    running install

**Comment by jasonriddell** [comment]
The codenvy/python27 image inherits from codenvy/shellinabox image, which explicitly sets the executing user to "user", I suspect that your issue is that the user "user" doesn't have permissions to  write to /usr/local/lib.

You can get round this by changing the executing user to root, run your privileged command and then change the user back to "user" i.e.

[...]
USER root
RUN pip install redis (or your command)
USER user
[...]

or alternatively include sudo in the pip command as this is also included as part of the codenvy/shellinabox image. 

[...]
RUN sudo pip install redis (or your command)
[...]

 Jason.
